Auto discover latest versions of supporting apps
MatthewVance/nginx-build pull request #77
Opened 2019-04-19 01:36 UTC by shmick

Eliminate the need to update this script when new versions of openssl 1.1.1, nginx, zlib, and pcre are released.

Credit also to @VirtuBox for the initial suggestion with nginx

2019-04-19 05:35 UTC, jellemdekker commented
Would it be possible to reuse the `source_*` variables from lines 32 to 35 in your addition? I'll try later today and report back.

On Apr 19, 2019 03:36, Steve M <notifications@github.com> wrote:

Eliminate the need to update this script when new versions of openssl 1.1.1, nginx, zlib, and pcre are released.

Credit also to @VirtuBox<https://github.com/VirtuBox> for the initial suggestion with nginx

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/MatthewVance/nginx-build/pull/77

Commit Summary

  *   Auto discover latest versions of supporting apps

File Changes

  *   M build-nginx.sh<https://github.com/MatthewVance/nginx-build/pull/77/files#diff-0> (15)

Patch Links:

  *   https://github.com/MatthewVance/nginx-build/pull/77.patch
  *   https://github.com/MatthewVance/nginx-build/pull/77.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/MatthewVance/nginx-build/pull/77>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ABLAU7SKHZE3IPERR6R5UVLPREOYBANCNFSM4HHBMAXA>.

2019-04-19 08:23 UTC, jellemdekker requested changes
I have optimized your code a little bit. If you move the code block with the `source_` variables to line 12, update the `version_` code block below it and leave out the other modifications, it works as well.

```sh
# Look up latest versions of each package
version_pcre=$(curl -sL ${source_pcre} | grep -Eo 'pcre\-[0-9.]+[0-9]' | sort -V | tail -n 1)
version_zlib=$(curl -sL ${source_zlib} | grep -Eo 'zlib\-[0-9.]+[0-9]' | sort -V | tail -n 1)
version_openssl=$(curl -sL ${source_openssl} | grep -Eo 'openssl\-[0-9.]+[a-z]?' | sort -V | tail -n 1)
version_nginx=$(curl -sL ${source_nginx} | grep -Eo 'nginx\-[0-9.]+[0-9]' | sort -V | tail -n 1)
```

EDIT: [Gist for clarification](https://gist.github.com/jellemdekker/c63305b88befec8f22365b74d9554b80). :)

2019-04-20 02:34 UTC, shmick commented
I like the gist you posted, @jellemdekker. The only issue I can see is that the nginx should be made to check for odd numbers in the major version field, or use the [download.html](http://nginx.org/en/download.html) link that always shows the mainline version at the top of the page.

2019-04-20 02:57 UTC, shmick commented
My regex-foo is pretty bad, but this looks like it should catch the odd numbered nginx versions `nginx\-[0-9.]+[13579][.0-9][0-9]{1,2}`

2019-04-20 12:06 UTC, jellemdekker commented
Perhaps I can help improve the regex if I understand better. Can you give an example of odd numbered nginx versions?

I noticed you had originally used download.html to find the latest nginx version. But I opted to stick with the original source link, because that's where the files are actually hosted. And because of this part of the code: `... | sort -V | tail -n 1`.

> -V, --version-sort
    natural sort of (version) numbers within text
[sort(1) - Linux man page](https://linux.die.net/man/1/sort)

As the version numbers are sorted from oldest to newest, we can use `tail -n 1` on that output to retrieve the latest version (from the last position of the array), thus always using the latest mainline version of nginx.

2019-04-20 16:04 UTC, shmick commented
There's a short period where the mainline branch isn't the newest ie: when v1.16.0 gets released prior to v1.17.0

2019-04-22 20:45 UTC, jellemdekker commented
I'm wondering whether or not we should restrict the regexes to certain versions, e.g.
- PCRE 8.x,
- nginx 1.x.x,
- OpenSSL 1.1.x.

Just to be sure that if a new major version is released (or minor version in the case of OpenSSL), the script won't break because the compilation process becomes out of date.

If the above isn't a valid concern, then in my opinion this pull request is ready to be merged.

2019-04-22 22:16 UTC, shmick commented
That can probably be it's own PR.

2019-04-22 22:44 UTC, MatthewVance commented
My main concern is making sure we're confident the regex will only track the mainline release. As @GainfulShrimp mentioned, it's possible for the mainline not to be the newest. We ran into that [before](https://github.com/MatthewVance/nginx-build/pull/4#issuecomment-214939233). 

@jellemdekker I like the idea of restricting the regexes to certain versions. I'm good with implementing that in a separate PR or including it as part of this one.

2019-04-22 22:50 UTC, shmick commented
@MatthewVance the regex for nginx will only match odd numbered versions for mainline.

Proof via [regexer](https://regexr.com/4cn99).

2019-04-22 23:13 UTC, MatthewVance commented
👍

2019-04-22 23:15 UTC, merged

2019-04-22 23:28 UTC, jellemdekker commented
Thanks for merging, but it looks like the 'source_*' code block is now in there twice.

On Apr 23, 2019 01:15, Matthew Vance <notifications@github.com> wrote:

Merged #77<https://github.com/MatthewVance/nginx-build/pull/77> into master.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/MatthewVance/nginx-build/pull/77#event-2292526669>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ABLAU7S7TNTCZGUP2ABKP43PRZBJBANCNFSM4HHBMAXA>.

2019-04-22 23:30 UTC, jellemdekker commented
Thanks for merging, but it looks like the 'source_*' code block is now in there twice.

2019-04-22 23:41 UTC, MatthewVance commented
Thanks for catching that. Not sure how I missed that when reviewing the
change diff. Thankfully it's an easy fix.

On Mon, Apr 22, 2019, 6:28 PM Jelle Dekker <notifications@github.com> wrote:

> Thanks for merging, but it looks like the 'source_*' code block is now in
> there twice.
>
> On Apr 23, 2019 01:15, Matthew Vance <notifications@github.com> wrote:
>
> Merged #77<https://github.com/MatthewVance/nginx-build/pull/77> into
> master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub<
> https://github.com/MatthewVance/nginx-build/pull/77#event-2292526669>, or
> mute the thread<
> https://github.com/notifications/unsubscribe-auth/ABLAU7S7TNTCZGUP2ABKP43PRZBJBANCNFSM4HHBMAXA
> >.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/MatthewVance/nginx-build/pull/77#issuecomment-485587426>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAUMHORCWRLD2RMPT45CWYLPRZCZNANCNFSM4HHBMAXA>
> .
>

2019-04-23 00:51 UTC, MatthewVance commented
Resolved with https://github.com/MatthewVance/nginx-build/commit/08e12b3808649edf3c2da071493d11ac4a3b7154.